admin_panel/urls.py
from django.urls import path

from .views import AdminPanelView, AdminProductDetailView, SetMeinProductPhotoView, DeleteProductPhotoView, \
    CreateProductPhotoView, CreateUpdateDiscountView, DeleteDiscountView, DeleteProductView, CreateProductPropertyView, \
    UpdateProductPropertyView, DeleteProductPropertyView, MoveUpProductPropertyView, MoveDownProductPropertyView

urlpatterns = [
    path('', AdminPanelView.as_view(), name="index"),
    path('product/<int:pk>/', AdminProductDetailView.as_view(), name="product-detail"),
    path("main-image/<int:pk>/", SetMeinProductPhotoView.as_view(), name="main-photo"),
    path('delete-image/<int:pk>/', DeleteProductPhotoView.as_view(), name="delete-photo"),
    path("create-photo/<int:pk>/", CreateProductPhotoView.as_view(), name="create-photo"),
    path("discount/<int:pk>/", CreateUpdateDiscountView.as_view(), name="discount"),
    path("delete-discount/<int:pk>/", DeleteDiscountView.as_view(), name="delete-discount"),
    path("delete-product/<int:pk>/", DeleteProductView.as_view(), name="delete-product"),
    path("create-property/<int:pk>/", CreateProductPropertyView.as_view(), name="create-property"),
    path("update-property/<int:pk>/", UpdateProductPropertyView.as_view(), name="update-property"),
    path("delete-property/<int:pk>/", DeleteProductPropertyView.as_view(), name="delete-property"),
    path("move-up-property/<int:pk>/", MoveUpProductPropertyView.as_view(), name="move-up-property"),
    path("move-down-property/<int:pk>/", MoveDownProductPropertyView.as_view(), name="move-down-property")
]

app_name = "admin_panel"

basket/urls.py
from django.urls import path

from basket.views import (
    BasketView,
    PlusItemFromBasketView,
    MinusItemFromBasketView,
    DeleteItemFromBasketView
)

urlpatterns = [
    path('', BasketView.as_view(), name="list"),
    path('plus-basket/<int:product_id>/', PlusItemFromBasketView.as_view(), name='plus_basket'),
    path('minus-basket/<int:product_id>/', MinusItemFromBasketView.as_view(), name='minus_basket'),
    path('delete-item-from-basket/<int:product_id>/', DeleteItemFromBasketView.as_view(), name="delete-item"),

]

app_name = "basket"

django_shop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from catalog.views import HomePageView
from django_shop import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_panel/', include("admin_panel.urls", namespace="admin-panel")),
    path('catalog/', include("catalog.urls", namespace="catalog")),
    path('products/', include("products.urls", namespace="products")),
    path('basket/', include("basket.urls", namespace="basket")),
    path('delivery/', include("logistic.urls", namespace="logistic")),
    path('payment/', include("payment.urls", namespace="payment")),
    path('orders/', include("orders.urls", namespace="orders")),
    path('reviews/', include("reviews.urls", namespace="reviews")),
    path('about-us/', include("site_detail.urls", namespace="site_detail")),
    path("contact-us-request-form/", include("support.urls", namespace="support")),
    path('', HomePageView.as_view(), name="home"),
] + static(
    settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0]
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path

from products.views import CreateProductView, ProductDitailView, ProductCustomerList

urlpatterns = [
    path('create/', CreateProductView.as_view(), name="create_product"),
    path('detail/<int:pk>/', ProductDitailView.as_view(), name="product_detail"),
    path('product-list/', ProductCustomerList.as_view(), name="product-list")
]

app_name = "products"

payment/models.py
from django.db import models

from logistic.models import DeliveryDetail
from orders.models import Order


class Payments(models.Model):
    class TransactionStatus:
        success = "success"
        pending = "pending"
        failed = "failed"

    TRANSACTION_STATUS = (
        (TransactionStatus.success, "Success"),
        (TransactionStatus.pending, "Pending"),
        (TransactionStatus.failed, "Failed"),
    )

    amount = models.DecimalField(max_digits=10, decimal_places=2)
    currency = models.CharField()
    delivery_ditail = models.ForeignKey(DeliveryDetail, on_delete=models.CASCADE, related_name="payment")
    data_created = models.DateTimeField(auto_created=True)
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name="payment")
    transaction_status = models.CharField(choices=TRANSACTION_STATUS, default=TransactionStatus.pending)

    def __str__(self):
        return str(self.amount) + " " + self.currency

products/models.py
import datetime

from django.db import models
from django.utils import timezone

from catalog.models import CatalogItem


class Product(models.Model):
    name = models.CharField(max_length=255, unique=True)
    brand = models.CharField(max_length=255, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    catalog_item = models.ForeignKey(CatalogItem, on_delete=models.CASCADE, related_name='products')
    price = models.DecimalField(max_digits=10, decimal_places=2)
    inventory = models.IntegerField(default=0)

    def __str__(self):
        return self.name

    @property
    def is_top(self):
        marks = []
        reviews = self.reviews.all()
        for review in reviews:
            if review.rating:
                marks.append(review.rating)
        if len(marks) == 0:
            return False
        if sum(marks) / len(marks) >= 4:
            return True
        return False


    @property
    def has_comments(self):
        reviews = self.reviews.all()
        for review in reviews:
            if review.comment:
                return True
        return False

    @property
    def has_discount(self):
        discounts = self.discounts.all()
        if discounts:
            for discount in discounts:
                if discount.start_date < timezone.now() < discount.end_date:
                    return True
        return False


    @property
    def get_discount_price(self):
        discounts = self.discounts.all()
        list_discounts = []
        for discount in discounts:
            if discount.start_date <= timezone.now() <= discount.end_date:
                list_discounts.append(discount.percentage)
        if not list_discounts:
            return None
        max_discount = max(list_discounts)
        return float(self.price) * (100 - max_discount) // 100

    @property
    def get_discount(self):
        discounts = self.discounts.all()
        list_discounts = []
        for discount in discounts:
            if discount.start_date <= timezone.now() <= discount.end_date:
                list_discounts.append(discount.percentage)
        if not list_discounts:
            return None
        return int(max(list_discounts))

    @property
    def get_comments_height(self):
        return self.attributes.all().count() * 40

    @property
    def get_discount_end_date(self):
        discount = self.discounts.all().first()
        if discount:
            return discount.end_date.strftime('%Y-%m-%d') if discount.end_date else None
        return None

    @property
    def get_discount_start_date(self):
        discount = self.discounts.all().first()
        if discount:
            return discount.start_date.strftime('%Y-%m-%d') if discount.start_date else None
        return None


class ProductAttribute(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='attributes')
    name = models.CharField(max_length=255)
    value = models.CharField(max_length=255)
    title = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.name}: {self.value}"

    class Meta:
        ordering = ['id']


def default_end_date():
    return datetime.datetime(9999, 1, 30)


class Discount(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='discounts')
    percentage = models.FloatField()
    start_date = models.DateTimeField(default=timezone.now)
    end_date = models.DateTimeField(default=default_end_date)

    def __str__(self):
        return self.percentage


class ProductImages(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to='product_images/')
    color = models.CharField(max_length=50, blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    main = models.BooleanField(default=False)

    def __str__(self):
        return self.image.url

    class Meta:
        ordering = ['-main', 'id']

products/views.py
from django.core.exceptions import FieldError
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q, Case, When, F, DecimalField, IntegerField, Value, Avg
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.template.loader import render_to_string
from django.utils import timezone
from django.views import generic
from django.views.generic.edit import CreateView

from catalog.models import CatalogItem
from products.forms import *
from .models import Product


class CreateProductView(CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'adminPanel/products/productItemForm.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        counter = 0
        if self.request.POST:
            data['images'] = ProductImagesFormset(self.request.POST, self.request.FILES, prefix='images')
            data['attributes'] = ProductAttributeFormset(self.request.POST, prefix='attributes')
            data['discounts'] = DiscountFormset(self.request.POST, prefix='discounts')
        else:
            data['images'] = ProductImagesFormset(prefix='images')
            data['attributes'] = ProductAttributeFormset(prefix='attributes')
            data['discounts'] = DiscountFormset(prefix='discounts')
        data['images_empty_form'] = ProductImagesFormset(prefix='images', queryset=ProductImages.objects.none())[0]
        data['attributes_empty_form'] = ProductAttributeFormset(prefix='attributes', queryset=ProductAttribute.objects.none())[0]
        data['discounts_empty_form'] = DiscountFormset(prefix='discounts', queryset=Discount.objects.none())[0]
        data["counter"] = counter
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        images = context['images']
        attributes = context['attributes']
        discounts = context['discounts']

        self.object = form.save()

        if images.is_valid():
            images.instance = self.object
            images.save()

        if attributes.is_valid():
            attributes.instance = self.object
            attributes.save()

        if discounts.is_valid():
            discounts.instance = self.object
            discounts.save()

        catalog_item_html = render_to_string('adminPanel/catalog/catalog-item.html', {'item': self.object})
        return JsonResponse({'status': 'success', 'html': catalog_item_html})

    def form_invalid(self, form):
        return JsonResponse({'status': 'error', 'errors': form.errors}, status=400)


class ProductDitailView(generic.View):
    template_name = "shop/product-detail.html"

    def get(self, requests, *args, **kwargs):
        product = get_object_or_404(Product, id=kwargs.get("pk"))
        context = {"product": product}
        return render(template_name=self.template_name, request=requests, context=context)


class ProductCustomerList(generic.TemplateView):
    template_name = 'shop/products.html'

    def get_context_data(self, **kwargs):
        context = super(ProductCustomerList, self).get_context_data(**kwargs)
        context["catalog_items"] = CatalogItem.objects.all()
        products = Product.objects.all().order_by('-inventory')
        context["brands"] = {product.brand for product in products if product.brand}
        prices = [
            product.price
            if product.get_discount_price is None
            else product.get_discount_price
            for product in products
        ]
        if not prices:
            prices = [0]
        context["min_price"] = min(prices)
        context["max_price"] = max(prices)
        filter_params = self.request.GET
        filter_q = Q()
        for key, value in filter_params.items():

            if key in [
                "q", 'price__gte', 'price__lte',
                "has_discount", "has_comments", "is_top",
                "ordering"
            ]:
                continue
            filter_q &= Q(**{key: value})
            print(filter_q)
            try:
                products = products.filter(filter_q)
            except FieldError as e:
                print(e)
                continue
        ordering = self.request.GET.get('ordering', None)
        if ordering:
            if ordering == "toMaxPrice":
                products = Product.objects.annotate(
                    current_price=Case(
                        When(
                            discounts__start_date__lte=timezone.now(),
                            discounts__end_date__gte=timezone.now(),
                            then=F('price') * (100 - F('discounts__percentage')) / 100
                        ),
                        default='price',
                        output_field=DecimalField(max_digits=10, decimal_places=2)
                    ),
                    inventory_order=Case(
                        When(inventory__lte=0, then=Value(1)),
                        default=Value(0),
                        output_field=IntegerField()
                    )
                ).order_by('inventory_order', 'current_price')
            if ordering == "toMinPrice":
                products = Product.objects.annotate(
                    current_price=Case(
                        When(
                            discounts__start_date__lte=timezone.now(),
                            discounts__end_date__gte=timezone.now(),
                            then=F('price') * (100 - F('discounts__percentage')) / 100
                        ),
                        default='price',
                        output_field=DecimalField(max_digits=10, decimal_places=2)
                    ),
                    inventory_order=Case(
                        When(inventory__lte=0, then=Value(1)),
                        default=Value(0),
                        output_field=IntegerField()
                    )
                ).order_by('inventory_order', '-current_price')

            if ordering == "byRating":
                products = Product.objects.annotate(
                    average_rating=Avg('reviews__rating'),
                    has_rating=Case(
                        When(average_rating__isnull=True, then=Value(1)),
                        default=Value(0),
                        output_field=IntegerField()
                    ),
                    inventory_order = Case(
                        When(inventory__lte=0, then=Value(1)),
                        default=Value(0),
                        output_field=IntegerField()
                    )
                ).order_by('inventory_order', 'has_rating', '-average_rating')
        exclude_ids = []
        has_comments = self.request.GET.get('has_comments', None)
        has_discount = self.request.GET.get('has_discount', None)
        price_gte = self.request.GET.get('price__gte', None)
        price_lte = self.request.GET.get('price__lte', None)
        is_top = self.request.GET.get('is_top',  None)
        for product in products:
            price = product.price if product.get_discount_price is None else product.get_discount_price
            if price_gte:
                if price < int(price_gte):
                    exclude_ids.append(product.id)
                    continue
            if price_lte:
                if price > int(price_lte):
                    exclude_ids.append(product.id)
            if has_discount:
                if product.has_discount is False:
                    exclude_ids.append(product.id)
            if has_comments:
                if product.has_comments is False:
                    exclude_ids.append(product.id)
            if is_top:
                if product.is_top is False:
                    exclude_ids.append(product.id)

        products = products.exclude(id__in=exclude_ids)

        product_filter = self.request.GET.get("q")
        if product_filter:
            products = products.filter(name__icontains=product_filter)

        paginator = Paginator(products, 12)
        page = self.request.GET.get('page')

        try:
            products = paginator.page(page)
        except PageNotAnInteger:
            products = paginator.page(1)
        except EmptyPage:
            products = paginator.page(paginator.num_pages)

        context["products"] = products

        return context

templates/adminPanel/products/product-detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <form method="post" action="{% url "admin-panel:delete-product" product.id %}">
    {% csrf_token %}
    <button type="submit" class="discount-form-submit delete-product">Delete</button>
  </form>
  <form method="post" action="{% url 'admin-panel:product-detail' product.id %}" >
  {% csrf_token %}
  <div style="display: flex">

  <div>
    {% for image in product.images.all %}
      {% if image.main %}
        <img class="productImageDitail" src="{{ image.image.url }}" alt="{{ product.name }}">
      {% endif %}
    {% empty %}
      <img class="productImageDitail" src="{% static 'images/default-product-item.png' %}" alt="{{ product.name }}">
    {% endfor %}
  </div>
  <div style="display: flex; flex-direction: column">
  <div style="display: flex">

  <div class="ditailInfProduct">

    <div class="ditailInfProductName" style="display: flex; align-items: center; margin-top: 10px; margin-left: 10px">
      <input class="ditailInfProductName" name="name" value="{{ product.name }}" style="flex-grow: 1; border-radius: 20px;">
      <button type="submit" class="edit-button save-button"></button>
    </div>

    <div class="prodDitail" {% if product.get_discount_price %}
      style="color: red; text-decoration: line-through;"
      {% else %} style="color: green;" {% endif %}
    ><span style="margin-right: 10px">Price: </span> <input class="priceInput" name="price" value="{{ product.price }}" style="flex-grow: 1;"> {{ site.get_currency_display }}
      <button type="submit" class="edit-button save-button"></button>
    </div>
  <div class="prodDitail" {% if product.get_discount_price %} {{ site.get_currency_display }}
      style="color: green;"
      {% else %} style="display: none;" {% endif %}
    >Discount price: {{ product.get_discount_price }} {{ site.get_currency_display }}
    </div>
  <div style="display: flex">
    <div class="prodDitail"><span style="margin-right: 10px">Inventory: </span> <input class="priceInput" name="inventory" value="{{ product.inventory }}" style="flex-grow: 1; border-radius: 20px;">
      <button type="submit" class="edit-button save-button"></button></div>

  </div>
    <div class="prodDitail"><span style="margin-right: 10px">Brand:</span> <input class="priceInput" name="brand" value="{{ product.brand }}" style="flex-grow: 1; border-radius: 20px;">
      <button type="submit" class="edit-button save-button"></button></div>
    <div style="display: flex">
      <div class="prodDitail">Rating:</div>
      <div class="starRatingList prodDitail"  data-product-id="{{ product.id }}">
            <span class="starList star1List" data-value="1">☆</span>
            <span class="starList star2List" data-value="2">☆</span>
            <span class="starList star3List" data-value="3">☆</span>
            <span class="starList star4List" data-value="4">☆</span>
            <span class="starList star5List" data-value="5">☆</span>

</div>
      </div>
  </div>
  <div class="ditailInfProduct" style="margin-left: 3vw;">
    <div class="ditailInfProductName">Description</div>
    <textarea class="descriptionText" name="description">{{ product.description }}</textarea>
     <button type="submit" class="edit-button save-button"></button>
  </div>
  </div>
 </form>
  <div class="imagesContainer">
   {% for image in product.images.all %}
     <div class="image-container">
     {% if image.main == True %}
        <img class="productImagesDitail" style="border: 5px solid green" src="{{ image.image.url }}" alt="{{ product.name }}">
     {% else %}
       <img class="productImagesDitail" src="{{ image.image.url }}" alt="{{ product.name }}">
     {% endif %}
     {% if image.main == True %}
     {% else %}
       <form method="post" action="{% url 'admin-panel:delete-photo' image.id %}">
       {% csrf_token %}
      <button class="delete-image-btn" action="submit">🗑️</button>
       </form>
     {% endif %}
     <form method="post" action="{% url 'admin-panel:main-photo' image.id %}">
     {% csrf_token %}
     {% if image.main == True %}
      <button class="set-main-image-btn" style="background-color: yellow; right: 24px" action="submit">★</button>
     {% else %}
      <button class="set-main-image-btn" action="submit">★</button>
     {% endif %}
     </form>
    </div>
  {% endfor %}
    <form>
      {% csrf_token %}
    <div class="productImagesDitail create-image">
      <input name="image" class="inputProductImage" style="display: none" type="file">
    </div>
    </form>
<script>
document.querySelector('.create-image').addEventListener('click', function() {
    event.stopPropagation();
  document.querySelector('.inputProductImage').click();
});

document.querySelector('.inputProductImage').addEventListener('change', function(event) {
  const file = event.target.files[0];
  if (file) {
    const formData = new FormData();
    formData.append('image', file);

    const uploadURL = "{% url 'admin-panel:create-photo' pk=product.pk %}";

    fetch(uploadURL, {
      method: 'POST',
      body: formData,
      headers: {
        'X-CSRFToken': document.querySelector('[name=csrfmiddlewaretoken]').value,
      },
    })
    .then(response => response.json())
    .then(data => {
      console.log('Success:', data);
      window.location.reload();
    })
    .catch(error => {
      console.error('Failed:', error);
      window.location.reload();
    });
  }
});
</script>
  </div>

  </div>
  </div>

  </form>

    <div style="display: flex">
    <div class="productPropertyTable">
      <h2 id="productPropertyTitle"> Product property </h2>

      <table>
      <thead>
    <tr>
      <th>Name</th>
      <th>Value</th>
      <th style="width: 30px">Title</th>
      <th style="width: 30px">Save</th>
      <th style="width: 30px">Up</th>
      <th style="width: 30px">Down</th>
      <th style="width: 30px">Delete</th>
    </tr>
  </thead>
  <tbody>
    {% for properys in product.attributes.all %}
      <tr>
      <div id="property{{ properys.id }}">
          <form method="post" action="{% url 'admin-panel:update-property' properys.id %}">
            {% csrf_token %}
          <td><input style="width: 95%" name="name" value="{{ properys.name }}"></td>
          <td><input style="width: 95%" name="value" value="{{ properys.value }}"></td>
          <td><input name="title" type="checkbox" {% if properys.title == True %}  checked="checked" {% endif %}></td>
          <td>

              <button type="submit">&#128190;</button>

          </td>
         </form>
      </div>
          <td>
            <form method="post" action="{% url "admin-panel:move-up-property" properys.id %}">
            {% csrf_token %}
              <button type="submit">&#11014;</button>
            </form>
          </td>
           <td>
            <form method="post" action="{% url "admin-panel:move-down-property" properys.id %}">
            {% csrf_token %}
              <button type="submit">&#11015;</button>
            </form>
          </td>
          <td>
            <form method="post" action="{% url "admin-panel:delete-property" properys.id %}">
            {% csrf_token %}
              <button type="submit">&#10060;</button>
            </form>
          </td>



      </tr>
    {% endfor %}
    <div id="createPropertyProd">
  <form method="post" action="{% url 'admin-panel:create-property' product.id %}">
  {% csrf_token %}
    <td><input style="width: 95%" name="name" minlength="1"></td>
    <td><input style="width: 95%" name="value"></td>
    <td><input name="title" type="checkbox" {% if properys.title == True %}  checked="checked" {% endif %}></td>
    <td colspan="4">

        <button style="margin-left: 85px" type="submit">&#128190;</button>

    </td>
  </form>
    </div>
  </tbody>
</table>

    </div>
    <div class="productCommentsTable" style="font-family: 'Texturina', serif">
      <h2 id="productPropertyTitle"> Discount </h2>

      <form method="post" action="{% url 'admin-panel:discount' product.id %}" class="discount-form-container">
        {% csrf_token %}
        <div class="discount-form-group">
            <label class="discount-form-label">Percentage:</label>
            <input type="number" name="percentage" value="{{ product.get_discount }}" min="0" max="99" class="discount-form-input">
        </div>
        <div class="discount-form-group">
            <label class="form-label">Start date:</label>
            <input type="date" name="start_date" value="{{ product.get_discount_start_date }}" class="discount-form-input">
        </div>
        <div class="discount-form-group">
            <label class="discount-form-label">End date:</label>
            <input type="date" name="end_date" value="{{ product.get_discount_end_date }}" class="discount-form-input">
        </div>
        <button type="submit" class="discount-form-submit">Submit</button>
    </form>
      <form method="post" action="{% url 'admin-panel:delete-discount' product.id %}">
          {% csrf_token %}
          <button type="submit" class="discount-form-submit delete-discount">Delete</button>
        </form>

    </div>
    </div>


  <script>
  $(document).ready(function() {
    $('.starRatingList').each(function() {
        var $starRatingList = $(this);
        var productId = $starRatingList.data("product-id");

        $.ajax({
            url: '/reviews/get-avg-rating/' + productId + '/',
            type: 'GET',
            dataType: 'json',
            success: function(data) {
                var avgRating = data.avg_rating;

                $starRatingList.find('span').each(function() {
                    var ratingValue = $(this).data('value');

                    $(this).css('background', 'none');
                    $(this).css('color', 'black');

                    if (ratingValue <= avgRating) {
                        $(this).css('color', 'yellow');
                    } else if (ratingValue - avgRating < 1) {
                        var fillPercentage = (avgRating - Math.floor(avgRating)) * 100;
                        $(this).css({
                            'background': 'linear-gradient(to right, yellow ' + fillPercentage + '%, black ' + fillPercentage + '%)',
                            '-webkit-background-clip': 'text',
                            'color': 'transparent'
                        });
                    }
                });
            },
            error: function(error) {
                console.log(error);
            }
        });
    });
});
  </script>
{% endblock %}

templates/adminPanel/products/product-item.html
{% load static %}

<div class="catalog-item productDetail" data-url="{% url 'admin-panel:product-detail' product.id %}">
  <div class="catalog-image-container">
<script>
    document.querySelectorAll('.productDetail').forEach(item => {
        item.addEventListener('click', function() {
            window.location.href = this.getAttribute('data-url');
        });
    });
</script>
<div>
  {% if product.images.all %}
    <div>
      {% for image in product.images.all %}
        {% if image.main == True %}
        <img class="productImage" src="{{ image.image.url }}" alt="{{ product.name }}">
        {% endif %}
      {% endfor %}
    </div>
  {% else %}
    <img class="productImage" src="{% static 'images/default-product-item.png' %}" alt="{{ product.name }}">
  {% endif %}
</div>
  <div class="productInfo">
    <span class="productName">{{ product.name }} </span>
    <span class="productName">Price: <span style="color: #4CAF50">{{ product.price }} {{ site.get_currency_display }} </span></span>
  </div>
  </div>
</div>