admin_panel/urls.py
from django.urls import path

from .views import AdminPanelView, AdminProductDetailView, SetMeinProductPhotoView, DeleteProductPhotoView, \
    CreateProductPhotoView, CreateUpdateDiscountView, DeleteDiscountView, DeleteProductView, CreateProductPropertyView, \
    UpdateProductPropertyView, DeleteProductPropertyView, MoveUpProductPropertyView, MoveDownProductPropertyView

urlpatterns = [
    path('', AdminPanelView.as_view(), name="index"),
    path('product/<int:pk>/', AdminProductDetailView.as_view(), name="product-detail"),
    path("main-image/<int:pk>/", SetMeinProductPhotoView.as_view(), name="main-photo"),
    path('delete-image/<int:pk>/', DeleteProductPhotoView.as_view(), name="delete-photo"),
    path("create-photo/<int:pk>/", CreateProductPhotoView.as_view(), name="create-photo"),
    path("discount/<int:pk>/", CreateUpdateDiscountView.as_view(), name="discount"),
    path("delete-discount/<int:pk>/", DeleteDiscountView.as_view(), name="delete-discount"),
    path("delete-product/<int:pk>/", DeleteProductView.as_view(), name="delete-product"),
    path("create-property/<int:pk>/", CreateProductPropertyView.as_view(), name="create-property"),
    path("update-property/<int:pk>/", UpdateProductPropertyView.as_view(), name="update-property"),
    path("delete-property/<int:pk>/", DeleteProductPropertyView.as_view(), name="delete-property"),
    path("move-up-property/<int:pk>/", MoveUpProductPropertyView.as_view(), name="move-up-property"),
    path("move-down-property/<int:pk>/", MoveDownProductPropertyView.as_view(), name="move-down-property")
]

app_name = "admin_panel"

basket/urls.py
from django.urls import path

from basket.views import (
    BasketView,
    PlusItemFromBasketView,
    MinusItemFromBasketView,
    DeleteItemFromBasketView
)

urlpatterns = [
    path('', BasketView.as_view(), name="list"),
    path('plus-basket/<int:product_id>/', PlusItemFromBasketView.as_view(), name='plus_basket'),
    path('minus-basket/<int:product_id>/', MinusItemFromBasketView.as_view(), name='minus_basket'),
    path('delete-item-from-basket/<int:product_id>/', DeleteItemFromBasketView.as_view(), name="delete-item"),

]

app_name = "basket"

django_shop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from catalog.views import HomePageView
from django_shop import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_panel/', include("admin_panel.urls", namespace="admin-panel")),
    path('catalog/', include("catalog.urls", namespace="catalog")),
    path('products/', include("products.urls", namespace="products")),
    path('basket/', include("basket.urls", namespace="basket")),
    path('delivery/', include("logistic.urls", namespace="logistic")),
    path('payment/', include("payment.urls", namespace="payment")),
    path('orders/', include("orders.urls", namespace="orders")),
    path('reviews/', include("reviews.urls", namespace="reviews")),
    path('about-us/', include("site_detail.urls", namespace="site_detail")),
    path("contact-us-request-form/", include("support.urls", namespace="support")),
    path('', HomePageView.as_view(), name="home"),
] + static(
    settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0]
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from orders.views import UserOrderListView, AdminOrderListView, ChangeOrderStatusView

urlpatterns = [
    path('user/', UserOrderListView.as_view(), name="user-order-list"),
    path('admin/', AdminOrderListView.as_view(), name="admin-order-list"),
    path('change-status/<int:id>/', ChangeOrderStatusView.as_view(), name="change-order-status")
]

app_name = "orders"

site_detail/urls.py
from django.urls import path

from site_detail.views import EditSiteInfoView, AboutUSView

urlpatterns = [
    path('edit-site-info/', EditSiteInfoView.as_view(), name="edit-site-info"),
    path("about-us/", AboutUSView.as_view(), name="about_us")
]

app_name = "site_detail"

support/urls.py
from django.urls import path

from support.views import ContactUsView, AdminSupportListView, SendSupportResponseView

urlpatterns = [
    path('contact-us-form/', ContactUsView.as_view(), name="contact-us"),
    path('admin-support/', AdminSupportListView.as_view(), name="admin-support"),
    path('send-support-response/<int:id>/', SendSupportResponseView.as_view(), name="send-support-response"),
]

app_name = "support"

orders/models.py
from django.db import models

from basket.models import Goods
from logistic.models import DeliveryDetail


class Order(models.Model):
    class OrderStatus:
        CREATED = "created"
        IN_PROGRESS = "in_progress"
        SHIPPED = "shipped"
        DELIVERED = "delivered"

    ORDER_STATUS_CHOICES = (
        (OrderStatus.CREATED, "Created"),
        (OrderStatus.IN_PROGRESS, "In Progress"),
        (OrderStatus.SHIPPED, "Shipped"),
        (OrderStatus.DELIVERED, "Delivered"),
    )

    delivery_status = models.CharField(
        max_length=20,
        choices=ORDER_STATUS_CHOICES,
        default=OrderStatus.CREATED
    )

    delivery_info = models.ForeignKey(DeliveryDetail, on_delete=models.CASCADE, related_name="order")
    goods = models.ManyToManyField(Goods, related_name="order", blank=True)
    user_id = models.CharField()
    data_created = models.DateTimeField(auto_created=True, blank=True, null=True)

    @property
    def get_total_price(self):
        transaction = self.payment.filter(transaction_status="success").first()
        if transaction:
            return self.payment.filter(transaction_status="success").first().amount
        return None

    @property
    def get_currency(self):
        transaction = self.payment.filter(transaction_status="success").first()
        if transaction:
            return self.payment.filter(transaction_status="success").first().currency
        return None

admin_panel/views.py
from datetime import datetime

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.utils.dateparse import parse_datetime
from django.views import generic

from catalog.models import CatalogItem
from products.models import Product, ProductImages, Discount, ProductAttribute


class AdminPanelView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'adminPanel/index.html'

    def get_context_data(self, **kwargs):
        context = super(AdminPanelView, self).get_context_data(**kwargs)
        catalog_items_list = CatalogItem.objects.all().order_by('-id')
        paginator = Paginator(catalog_items_list, 11)
        page = self.request.GET.get('page')

        try:
            catalog_items = paginator.page(page)
        except PageNotAnInteger:
            catalog_items = paginator.page(1)
        except EmptyPage:
            catalog_items = paginator.page(paginator.num_pages)

        context['catalog_items'] = catalog_items
        product_filter = self.request.GET.get("q")
        product_items_list = Product.objects.all().order_by('-id')
        if product_filter:
            product_items_list = product_items_list.filter(name__contains=product_filter)
        paginator = Paginator(product_items_list, 11)
        page = self.request.GET.get('page')

        try:
            products = paginator.page(page)
        except PageNotAnInteger:
            products = paginator.page(1)
        except EmptyPage:
            products = paginator.page(paginator.num_pages)

        context['products'] = products
        return context


class AdminProductDetailView(generic.View):
    template_name = "adminPanel/products/product-detail.html"

    def get(self, requests, *args, **kwargs):
        product = get_object_or_404(Product, id=kwargs.get("pk"))
        context = {"product": product}
        return render(template_name=self.template_name, request=requests, context=context)

    def post(self, requests, *args, **kwargs):
        product = get_object_or_404(Product, id=kwargs.get("pk"))
        context = {"product": product}
        for key, value in requests.POST.items():
            if hasattr(product, key):
                setattr(product, key, value)
        product.save()
        return render(template_name=self.template_name, request=requests, context=context)


class SetMeinProductPhotoView(generic.View):

    def post(self, requests, *args, **kwargs):

        image_id = self.kwargs.get("pk")
        product = Product.objects.get(images__id=image_id)
        for image in product.images.all():
            if image_id == image.id:
                image.main = True
            else:
                image.main = False
            image.save()
        return HttpResponseRedirect(reverse('admin_panel:product-detail', args=[product.pk]))


class DeleteProductPhotoView(generic.View):

    def post(self, requests, *args, **kwargs):
        image_id = self.kwargs.get("pk")
        product = Product.objects.get(images__id=image_id)
        ProductImages.objects.filter(id=image_id).delete()
        return HttpResponseRedirect(reverse('admin_panel:product-detail', args=[product.pk]))


class CreateProductPhotoView(generic.View):

    def post(self, requests, *args, **kwargs):
        product = get_object_or_404(Product, id=kwargs.get("pk"))
        image = self.request.FILES.get("image")
        if image:
            if product.images.all().count() == 0:
                ProductImages.objects.create(product=product, image=image, main=True)
            else:
                ProductImages.objects.create(product=product, image=image)
        return HttpResponseRedirect(reverse('admin_panel:product-detail', args=[product.pk]))


class CreateUpdateDiscountView(generic.View):

    def post(self, requests, *args, **kwargs):
        product = get_object_or_404(Product, id=kwargs.get("pk"))
        discount = Discount.objects.filter(product=product).first()
        percentage = requests.POST.get("percentage")
        if percentage and not discount:
            discount = Discount.objects.create(product=product, percentage=percentage)
        for key, value in requests.POST.items():
            if hasattr(discount, key):
                if isinstance(getattr(discount, key), datetime):
                    parsed_value = parse_datetime(value)
                    if parsed_value is not None:
                        setattr(discount, key, parsed_value)
                else:
                    setattr(discount, key, value)
        discount.save()
        return HttpResponseRedirect(reverse('admin_panel:product-detail', args=[product.pk]))


class DeleteDiscountView(generic.View):

    def post(self, requests, *args, **kwargs):
        product = get_object_or_404(Product, id=self.kwargs.get("pk"))
        Discount.objects.filter(product=product).delete()
        return HttpResponseRedirect(reverse('admin_panel:product-detail', args=[product.pk]))


class DeleteProductView(generic.View):

    def post(self, requests, *args, **kwargs):
        product = get_object_or_404(Product, id=self.kwargs.get("pk"))
        product.delete()
        return HttpResponseRedirect(reverse('admin_panel:index'))


class CreateProductPropertyView(generic.View):

    def post(self, requests, *args, **kwargs):
        product = get_object_or_404(Product, id=self.kwargs.get("pk"))
        if self.request.POST.get("name"):
            ProductAttribute.objects.create(
                product=product,
                name=self.request.POST.get("name"),
                value=self.request.POST.get("value"),
                title=True if self.request.POST.get("title") else False,
            )
        url = reverse('admin_panel:product-detail', args=[product.pk]) + '#createPropertyProd'
        return HttpResponseRedirect(url)


class UpdateProductPropertyView(generic.View):

    def post(self, requests, *args, **kwargs):
        product_property = get_object_or_404(ProductAttribute, id=self.kwargs.get("pk"))
        product = Product.objects.get(attributes=product_property)
        setattr(product_property, "title", False)
        for key, value in requests.POST.items():
            if hasattr(product_property, key):
                if key != "title":
                    setattr(product_property, key, value)
                else:
                    if value == "on":
                        setattr(product_property, key, True)
        product_property.save()

        url = reverse('admin_panel:product-detail', args=[product.pk]) + '#property' + str(product_property.id)
        return HttpResponseRedirect(url)


class DeleteProductPropertyView(generic.View):

    def post(self, requests, *args, **kwargs):
        product_property = get_object_or_404(ProductAttribute, id=self.kwargs.get("pk"))
        product = Product.objects.get(attributes=product_property)
        product_property.delete()
        url = reverse('admin_panel:product-detail', args=[product.pk]) + '#createPropertyProd'
        return HttpResponseRedirect(url)


class MoveUpProductPropertyView(generic.View):

    def post(self, requests, *args, **kwargs):
        product_property = get_object_or_404(ProductAttribute, id=self.kwargs.get("pk"))
        product = Product.objects.get(attributes=product_property)
        attributes = ProductAttribute.objects.filter(product=product).exclude(id__gte=product_property.id)
        attributes_id = []
        for attribute in attributes:
            attributes_id.append(attribute.id)
        if attributes_id:
            max_attributes_id = max(attributes_id)
            attribute_max_id = ProductAttribute.objects.get(id=max_attributes_id)
            attribute_max_id.id, product_property.id = product_property.id, attribute_max_id.id
            attribute_max_id.save()
            product_property.save()
        url = reverse('admin_panel:product-detail', args=[product.pk]) + '#property' + str(product_property.id)
        return HttpResponseRedirect(url)


class MoveDownProductPropertyView(generic.View):

    def post(self, requests, *args, **kwargs):
        product_property = get_object_or_404(ProductAttribute, id=self.kwargs.get("pk"))
        product = Product.objects.get(attributes=product_property)
        attributes = ProductAttribute.objects.filter(product=product).exclude(id__lte=product_property.id)
        attributes_id = []
        for attribute in attributes:
            attributes_id.append(attribute.id)
        if attributes_id:
            min_attributes_id = min(attributes_id)
            attribute_min_id = ProductAttribute.objects.get(id=min_attributes_id)
            attribute_min_id.id, product_property.id = product_property.id, attribute_min_id.id
            attribute_min_id.save()
            product_property.save()
        url = reverse('admin_panel:product-detail', args=[product.pk]) + '#property' + str(product_property.id)
        return HttpResponseRedirect(url)

templates/adminPanel/index.html
{% extends 'base.html' %}

{% block content %}
  <div class="grid-container">
  <div class="grid-item left">
    <button class="toggleButton">To category items</button>
    <h1 class="h1-admin-panel">
      <span>C</span><span>a</span><span>t</span><span>a</span><span>l</span><span>o</span><span>g</span>
      <span>i</span><span>t</span><span>a</span><span>m</span><span>s</span>
    </h1>
  <div id="catalogItemsContainer">
    <button id="addCatalogItemBtn">
      <div></div>
    </button>


    {% for item in catalog_items %}
      {% include 'adminPanel/catalog/catalog-item.html' with item=item %}
    {% endfor %}
</div>

<div class="pagination">
  <span class="step-links">
    {% if catalog_items.has_previous %}
      <a href="?page=1">&laquo; first</a>
      <a href="?page={{ catalog_items.previous_page_number }}">previous</a>
    {% endif %}

    <span class="current">
      Page {{ catalog_items.number }} of {{ catalog_items.paginator.num_pages }}.
    </span>

    {% if catalog_items.has_next %}
      <a href="?page={{ catalog_items.next_page_number }}">next</a>
      <a href="?page={{ catalog_items.paginator.num_pages }}">last &raquo;</a>
    {% endif %}
  </span>
</div>
    <div id="notification" class="notification"></div>
    <div id="catalogItemModal" class="modal">
    <div id="catalogItemModalContent" class="modal-content">
    </div>
  </div>
  </div>

  <div class="grid-item right">
     <button class="toggleButton">To products</button>
    <h1 class="h1-admin-panel"><span>G</span><span>o</span><span>o</span><span>d</span><span>s</span></h1>
  <div class="findContainer">
  <form style="width: 75%" action="?" method="get">
    <input class="goodsFinder" type="text" name="q" value="{{  request.GET.q|default_if_none:''}}">
    <button class="findGoods" type="submit"></button>
  </form>
</div>

      <div id="catalogItemsContainer">
     <button id="addProductItemBtn">
      <div></div>
    </button>
        {% for product in products %}
      {% include 'adminPanel/products/product-item.html' with product=product %}
    {% endfor %}
      </div>
    <div class="pagination">
  <span class="step-links">
    {% if products.has_previous %}
      <a href="?{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}&page=1">&laquo; first</a>
      <a href="?{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}&page={{ products.previous_page_number }}">previous</a>
    {% endif %}

    <span class="current">
      Page {{ products.number }} of {{ products.paginator.num_pages }}.
    </span>

    {% if products.has_next %}
      <a href="?{% for key, value in request.GET.items %}&{{ key }}={{ value }}{% endfor %}&page={{ products.next_page_number }}">next</a>
      <a href="?{% for key, value in request.GET.items %}&{{ key }}={{ value }}{% endfor %}&page={{ products.paginator.num_pages }}">last &raquo;</a>
    {% endif %}
  </span>
</div>

    <div id="catalogItemModal" class="modal">
      <div id="catalogItemModalContent" class="modal-content"></div>
    </div>
  </div>
</div>

{% endblock %}

templates/adminPanel/order-list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  {% for order in order_list %}
    <div class="orderAdmin"
         {% if order.delivery_status != "delivered" %}
           style="border: 3px solid red"
         {% else %}
         style="border: 3px solid green"
         {% endif %}
    >
      <div class="orderDivContainer">
        <div class="titleOrderDelivery">Delivery Detail</div>
        <div>Email: {{ order.delivery_info.email }}</div>
        <div>Phone: {{ order.delivery_info.phone }}</div>
        <div>Name: {{ order.delivery_info.first_name }} {{ order.delivery_info.last_name }}</div>
        <div>Country: {{ order.delivery_info.country }}</div>
        <div>State/Province: {{ order.delivery_info.state_province }}</div>
        <div>City: {{ order.delivery_info.city }}</div>
        <div>Street address: {{ order.delivery_info.street_address }}</div>
        <div>Postal code: {{ order.delivery_info.postal_code }}</div>
      </div>
      <div class="orderDivContainer">
        {% for product in order.goods.all %}
          <div class="productOrderContainerAdmin">
            <div>
                {% if product.product.images.all %}
                  <div>
                    {% for image in product.product.images.all %}
                      {% if image.main == True %}
                      <img class="productImageOrderAdmin" src="{{ image.image.url }}" alt="{{ product.name }}">
                      {% endif %}
                    {% endfor %}
                      </div>
                    {% else %}
                      <img class="productImageOrderAdmin" src="{% static 'images/default-product-item.png' %}" alt="{{ product.name }}">
                    {% endif %}
                  </div>
          <div style="margin: 20px">
            <div>Name: {{ product.product.name }}</div>
            <div>Amount: {{ product.amount }}</div>
          </div>
          </div>

        {% endfor %}
      </div>
     <div class="orderDivContainer">
       <div style="display: flex">
         <div class="statusOrder">
            <div class="scaleElem scaleElem1" style="background-color: #4CAF50">Order created</div>
            <div class="scaleElem scaleElem2" {% if order.delivery_status != 'created' %}style="background-color: #4CAF50"{% endif %}>Take in work</div>
            <div class="scaleElem scaleElem3" {% if order.delivery_status == 'shipped' or order.delivery_status == 'delivered' %}style="background-color: #4CAF50"{% endif %}>Send</div>
            <div class="scaleElem scaleElem4" {% if order.delivery_status == 'delivered' %}style="background-color: #4CAF50"{% endif %}>Delivered</div>
         </div>
         <div class="statusOrder">
           <div class="scaleElem scaleElem1" style="background-color: #f3e9f7;">
             <form method="post" action="{% url 'orders:change-order-status' order.id %}">
               {% csrf_token %}
               <input type="hidden" name="delivery_status" value='created'>
               <button  class="form-button" type="submit">Chose</button>
             </form>
           </div>
           <div class="scaleElem scaleElem1" style="background-color: #f3e9f7;">
             <form method="post" action="{% url 'orders:change-order-status' order.id %}">
               {% csrf_token %}
               <input type="hidden" name="delivery_status" value='in_progress'>
               <button  class="form-button" type="submit">Chose</button>
             </form>
           </div>
           <div class="scaleElem scaleElem1" style="background-color: #f3e9f7;">
            <form method="post" action="{% url 'orders:change-order-status' order.id %}">
               {% csrf_token %}
               <input type="hidden" name="delivery_status" value='shipped'>
               <button  class="form-button" type="submit">Chose</button>
             </form>
           </div>
           <div class="scaleElem scaleElem1" style="background-color: #f3e9f7;">
             <form method="post" action="{% url 'orders:change-order-status' order.id %}">
               {% csrf_token %}
               <input type="hidden" name="delivery_status" value='delivered'>
               <button  class="form-button" type="submit">Chose</button>
             </form>
           </div>
         </div>
       </div>
     </div>
    </div>
  {% endfor %}
    <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">&laquo; Previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Next &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

templates/adminPanel/payments-history.html
{% extends 'base.html' %}

{% block content %}
  <table>
  <thead>
    <tr>
      <th class="thTransactionHeader">ID</th>
      <th class="thTransactionHeader">Email</th>
      <th class="thTransactionHeader">Order ID</th>
      <th class="thTransactionHeader">Amount</th>
      <th class="thTransactionHeader">Currency</th>
      <th class="thTransactionHeader">Date Created</th>
      <th class="thTransactionHeader">Transaction Status</th>
    </tr>
  </thead>
  <tbody>
    {% for payment in payments_list %}
    <tr>
      <td>{{ payment.id }}</td>
      <td>{{ payment.delivery_ditail.email }}</td>
      <td>{{ payment.order.id }}</td>
      <td>{{ payment.amount }}</td>
      <td>{{ payment.currency }}</td>
      <td>{{ payment.data_created }}</td>
      <td {% if payment.transaction_status == "success" %} style="background-color: green" {% else %}style="background-color: red" {% endif %}>
        {{ payment.transaction_status }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>


  {% if not payments_list %}
      {% include 'includes/orderEmptyPage.html' %}
    <style>.ulOrder{display: none}</style>
  {% endif %}
  <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">&laquo; Previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Next &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

templates/adminPanel/site-info.html
{% extends 'base.html' %}

{% block content %}
  <div>
  <h1 id="siteInfoEdit">Site information</h1>

    <form method="post" action="{% url 'site_detail:edit-site-info' %}" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="siteEditInfo">
      <div class="siteEditInfoDiv" style="display: flex">
        <div style="text-align: left">Site name:</div>
        <input class="siteEditInfoInput" name="site_name" value="{{ site.site_name }}">
        <button class="siteEditInfoButton" type="submit">&#128190;</button>
      </div>
      <div class="siteEditInfoDiv" style="display: flex">
        <div style="text-align: left">Logo:</div>
        <input class="siteEditInfoInput" type="file" name="logo"  {% if site.logo %} value="{{ site.logo.url }}" {% endif %}>
        <button class="siteEditInfoButton" type="submit">&#128190;</button>
      </div>
      <div class="siteEditInfoDiv" style="display: flex">
        <div style="text-align: left" >Currency:</div>
          <select class="siteEditInfoInput" name="currency" value="{{ site.currency }}">
            <option value="uan" {% if site.currency == "uan" %}selected{% endif %}>₴ - UAN</option>
            <option value="usd" {% if site.currency == "usd" %}selected{% endif %}>$ - USD</option>
            <option value="euro" {% if site.currency == "euro" %}selected{% endif %}>€ - EURO</option>
          </select>
         <button class="siteEditInfoButton" type="submit">&#128190;</button>
      </div>
      <div class="siteEditInfoDiv" style="display: flex">
        <div style="text-align: left">Email:</div>
        <input class="siteEditInfoInput" name="email" value="{{ site.email }}">
        <button class="siteEditInfoButton" type="submit">&#128190;</button>
      </div>
      <div class="siteEditInfoDiv" style="display: flex">
        <div style="text-align: left">Stripe public key:</div>
        <input class="siteEditInfoInput" name="stripe_public_key" value="{{ site.stripe_public_key }}">
        <button class="siteEditInfoButton" type="submit">&#128190;</button>
      </div>
      <div class="siteEditInfoDiv" style="display: flex">
        <div style="text-align: left">Stripe private key:</div>
        <input class="siteEditInfoInput" name="stripe_private_key" value="{{ site.stripe_private_key }}">
        <button class="siteEditInfoButton" type="submit">&#128190;</button>
      </div>

      <div class="siteEditInfoDiv" style="display: flex">
        <div style="text-align: left">About us title:</div>
        <input class="siteEditInfoInput" name="about_us_title" value="{{ site.about_us_title }}">
        <button class="siteEditInfoButton" type="submit">&#128190;</button>
      </div>
      <div class="siteEditInfoDiv" style="display: flex">
        <div style="text-align: left">About us description:</div>
        <textarea class="siteEditInfoInput" name="about_us_description" value="{{ site.about_us_description }}"></textarea>
        <button class="siteEditInfoButton" type="submit">&#128190;</button>
      </div>
      <div class="siteEditInfoDiv" style="display: flex">
        <div style="text-align: left">About us image:</div>
        <input class="siteEditInfoInput" type="file" name="about_us_image" {% if site.about_us_image %} value="{{ site.about_us_image.url }}"{% endif %}>
        <button class="siteEditInfoButton" type="submit">&#128190;</button>
      </div>
</div>
    </form>
  </div>
{% endblock %}

templates/adminPanel/supportPage.html
{% extends 'base.html' %}

{% block content %}
  <div style="display: flex; flex-wrap: wrap;">
  {% for support in supportrequest_list %}
    <div class="supportContainer" {% if support.response_send  %} style="border: 3px solid green" {% else %} style="border: 3px solid red" {% endif %}>
    <div class="supportTitle">Request</div>
    <div>Name: {{ support.name }}</div>
    <div>Email: {{ support.email }}</div>
    <div>Topic: {{ support.topic }}</div>
    <div><textarea class="supportText" disabled="true"> {{ support.payload }}</textarea></div>
    <div style="text-align: right">Date: {{ support.date_created }}</div>
    <form method="post" action="{% url 'support:send-support-response' support.id %}">
      {% csrf_token %}
      <div class="supportTitle">Response</div>
      <div><textarea name="response" class="supportText" {% if support.response_send %} disabled="true" {% endif %}>{{ support.response }} </textarea></div>
      <div style="display: flex; justify-content: center; margin: 3px">
        {% if not support.response_send  %}
          <button style="align-items: center" type="submit" class="formButton">Send</button>
        {% endif %}</div>
    </form>

    </div>
  {% endfor %}
  </div>
    <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">&laquo; Previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Next &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}