basket/urls.py
from django.urls import path

from basket.views import (
    BasketView,
    PlusItemFromBasketView,
    MinusItemFromBasketView,
    DeleteItemFromBasketView
)

urlpatterns = [
    path('', BasketView.as_view(), name="list"),
    path('plus-basket/<int:product_id>/', PlusItemFromBasketView.as_view(), name='plus_basket'),
    path('minus-basket/<int:product_id>/', MinusItemFromBasketView.as_view(), name='minus_basket'),
    path('delete-item-from-basket/<int:product_id>/', DeleteItemFromBasketView.as_view(), name="delete-item"),

]

app_name = "basket"

django_shop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from catalog.views import HomePageView
from django_shop import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_panel/', include("admin_panel.urls", namespace="admin-panel")),
    path('catalog/', include("catalog.urls", namespace="catalog")),
    path('products/', include("products.urls", namespace="products")),
    path('basket/', include("basket.urls", namespace="basket")),
    path('delivery/', include("logistic.urls", namespace="logistic")),
    path('payment/', include("payment.urls", namespace="payment")),
    path('orders/', include("orders.urls", namespace="orders")),
    path('reviews/', include("reviews.urls", namespace="reviews")),
    path('about-us/', include("site_detail.urls", namespace="site_detail")),
    path("contact-us-request-form/", include("support.urls", namespace="support")),
    path('', HomePageView.as_view(), name="home"),
] + static(
    settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0]
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from orders.views import UserOrderListView, AdminOrderListView, ChangeOrderStatusView

urlpatterns = [
    path('user/', UserOrderListView.as_view(), name="user-order-list"),
    path('admin/', AdminOrderListView.as_view(), name="admin-order-list"),
    path('change-status/<int:id>/', ChangeOrderStatusView.as_view(), name="change-order-status")
]

app_name = "orders"

payment/urls.py
from django.urls import path

from payment.views import CreatePaymentAPIView, PaymentHistoryView

urlpatterns = [
    path('create-payment/', CreatePaymentAPIView.as_view(), name='create-payment'),
    path('history/', PaymentHistoryView.as_view(), name="payment-history")
]

app_name = "payment"

products/urls.py
from django.urls import path

from products.views import CreateProductView, ProductDitailView, ProductCustomerList

urlpatterns = [
    path('create/', CreateProductView.as_view(), name="create_product"),
    path('detail/<int:pk>/', ProductDitailView.as_view(), name="product_detail"),
    path('product-list/', ProductCustomerList.as_view(), name="product-list")
]

app_name = "products"

support/urls.py
from django.urls import path

from support.views import ContactUsView, AdminSupportListView, SendSupportResponseView

urlpatterns = [
    path('contact-us-form/', ContactUsView.as_view(), name="contact-us"),
    path('admin-support/', AdminSupportListView.as_view(), name="admin-support"),
    path('send-support-response/<int:id>/', SendSupportResponseView.as_view(), name="send-support-response"),
]

app_name = "support"

templates/includes/admin_header.html
{% load static %}

<header id="header">

  <div class="header-left">
  <a href="{% url 'home' %}">
    {% if site.logo %}
        <img id='logo' class="logo" src="{{ site.logo.url }}" alt="logo">
    {% else %}
        <img id='logo' class="logo" src="{% static 'images/logo.png' %}" alt="logo">
    {% endif %}
  </a>
      {% if site.site_name %}
       <span class="company-name"> {{ site.site_name }}</span>
    {% else %}
        <span class="company-name">Trerddfy</span>
    {% endif %}

       <button class="admin-button admin-button-panel" onclick="toggleHeaders()" style="margin-right: 20px">
         <span>Site</span>
       </button>
  </div>
  <div class="burger-menu" onclick="toggleAdminMenu()">
    <i id="burger" class="fas fa-bars burger"></i>
  </div>
  <nav id="navigation" class="admin-navigation">
    <ul id="navigation-list">
      <li class="nav-item first-nav-item"><a href="{% url 'site_detail:edit-site-info' %}"><i class="fas fa-info-circle"></i><span> Site info</span></a></li>
      <li class="nav-item"><a href="{% url 'admin-panel:index' %}"><i class="fas fa-box-open"></i><span> Products info</span></a></li>
      <li class="nav-item"><a href="{% url 'orders:admin-order-list' %}"><i class="fas fa-shopping-cart"></i><span> Orders</span></a></li>
      <li class="nav-item"><a href="{% url 'payment:payment-history' %}"><i class="fas fa-money-bill-wave"></i><span> Transactions</span></a></li>
      <li class="nav-item"><a href="{% url 'support:admin-support' %}"><i class="fas fa-life-ring"></i><span> Support</span></a></li>
    </ul>
  </nav>
</header>

templates/includes/basketEmptyPage.html
{% load static %}
<div id="emptyBasket">
  <div>
    <div id="basketWarnText">Your basket is empty!!!</div>
    <img id="basketEmptyImg" src="{% static 'images/emptyBasket.png' %}" alt="empty basket">
    <button class="returnBack" onclick="window.history.back()">Return back</button>
  </div>
</div>

templates/includes/header.html
{% load static %}

<header id="header" >
<a href="{% url 'home' %}">
     {% if site.logo %}
        <img id='logo' class="logo" src="{{ site.logo.url }}" alt="logo">
    {% else %}
        <img id='logo' class="logo" src="{% static 'images/logo.png' %}" alt="logo">
    {% endif %}
</a>
    {% if site.site_name %}
       <span class="company-name"> {{ site.site_name }}</span>
    {% else %}
        <span class="company-name">Trerddfy</span>
    {% endif %}

  {% if user.is_superuser %}
    <button class="admin-button" onclick="toggleHeaders()">
      <span>Admin panel</span>
    </button>
  {% endif %}
  <div class="burger-menu" onclick="toggleMenu()">
    <i id="burger" class="fas fa-bars"></i>
  </div>
    <nav id="navigation">
      <ul id="navigation-list">
        <li class="nav-item first-nav-item"><a href="{% url 'home' %}"><i class="fas fa-home"></i><span> Home</span></a></li>
        <li class="nav-item"><a href="{% url 'products:product-list' %}"><i class="fas fa-box"></i><span> Products</span></a></li>
        <li class="nav-item"><a href="{% url 'site_detail:about_us' %}"><i class="fas fa-users"></i><span> About Us</span></a></li>
        <li class="nav-item"><a href="{% url 'orders:user-order-list' %}"><i class="fas fa-shopping-cart"></i><span> Orders</span></a></li>
        <li class="nav-item"><a href="{% url 'support:contact-us' %}"><i class="fas fa-headset"></i><span> Support</span></a></li>
      </ul>
    </nav>
  {% if user.is_superuser == False %}
    <div id="basket"><a href="{% url 'basket:list' %}"><i id="mainBasketIcon" class="fas fa-shopping-basket fa-2x"></i></a></div>

  <script>
  function getCookiesObject() {
  const cookies = document.cookie.split(';').map(cookie => cookie.trim());

  const cookiesObject = {};

  for (const cookie of cookies) {
    const [name, value] = cookie.split('=');
    cookiesObject[name] = value;
  }

  return cookiesObject;
}
let amountGoods = 0;
const allCookies = getCookiesObject();

for (const key in allCookies) {
  if (!isNaN(+allCookies[key])) {

    amountGoods += parseInt(allCookies[key]);
  }
}

const mainBasket = document.getElementById("mainBasketIcon");
mainBasket.innerText = amountGoods;

</script>

  {% endif %}
</header>

templates/includes/orderEmptyPage.html
{% load static %}
<div id="emptyBasket">
  <div>
    <div id="basketWarnText">You haven't orders yet!!!</div>
    <img id="basketEmptyImg" src="{% static 'images/emptyBasket.png' %}" alt="empty basket">
    <button class="returnBack" onclick="window.history.back()">Return back</button>
  </div>
</div>