basket/urls.py
from django.urls import path

from basket.views import (
    BasketView,
    PlusItemFromBasketView,
    MinusItemFromBasketView,
    DeleteItemFromBasketView
)

urlpatterns = [
    path('', BasketView.as_view(), name="list"),
    path('plus-basket/<int:product_id>/', PlusItemFromBasketView.as_view(), name='plus_basket'),
    path('minus-basket/<int:product_id>/', MinusItemFromBasketView.as_view(), name='minus_basket'),
    path('delete-item-from-basket/<int:product_id>/', DeleteItemFromBasketView.as_view(), name="delete-item"),

]

app_name = "basket"

logistic/urls.py
from django.urls import path

from logistic.views import CreateUpdateDetailDeliveryView

urlpatterns = [
    path('detail/', CreateUpdateDetailDeliveryView.as_view(), name="create-update-delivery-ditail"),
]

app_name = "logistic"

payment/urls.py
from django.urls import path

from payment.views import CreatePaymentAPIView, PaymentHistoryView

urlpatterns = [
    path('create-payment/', CreatePaymentAPIView.as_view(), name='create-payment'),
    path('history/', PaymentHistoryView.as_view(), name="payment-history")
]

app_name = "payment"

products/urls.py
from django.urls import path

from products.views import CreateProductView, ProductDitailView, ProductCustomerList

urlpatterns = [
    path('create/', CreateProductView.as_view(), name="create_product"),
    path('detail/<int:pk>/', ProductDitailView.as_view(), name="product_detail"),
    path('product-list/', ProductCustomerList.as_view(), name="product-list")
]

app_name = "products"

support/urls.py
from django.urls import path

from support.views import ContactUsView, AdminSupportListView, SendSupportResponseView

urlpatterns = [
    path('contact-us-form/', ContactUsView.as_view(), name="contact-us"),
    path('admin-support/', AdminSupportListView.as_view(), name="admin-support"),
    path('send-support-response/<int:id>/', SendSupportResponseView.as_view(), name="send-support-response"),
]

app_name = "support"

basket/models.py
from _decimal import Decimal

from django.db import models

from products.models import Product


class Goods(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="goods")
    amount = models.PositiveSmallIntegerField(default=1)

    def __str__(self):
        return f"{self.product.name} - {self.amount}"

    @property
    def get_total(self):
        if self.product.get_discount_price:
            return self.amount * Decimal(self.product.get_discount_price)
        return self.amount * self.product.price


class Basket(models.Model):
    goods = models.ManyToManyField('Goods', related_name="basket")
    user_id = models.CharField(unique=True)

    def __str__(self):
        return self.user_id

    @property
    def get_basket_total_price(self):
        return sum(good.get_total for good in self.goods.all())

orders/models.py
from django.db import models

from basket.models import Goods
from logistic.models import DeliveryDetail


class Order(models.Model):
    class OrderStatus:
        CREATED = "created"
        IN_PROGRESS = "in_progress"
        SHIPPED = "shipped"
        DELIVERED = "delivered"

    ORDER_STATUS_CHOICES = (
        (OrderStatus.CREATED, "Created"),
        (OrderStatus.IN_PROGRESS, "In Progress"),
        (OrderStatus.SHIPPED, "Shipped"),
        (OrderStatus.DELIVERED, "Delivered"),
    )

    delivery_status = models.CharField(
        max_length=20,
        choices=ORDER_STATUS_CHOICES,
        default=OrderStatus.CREATED
    )

    delivery_info = models.ForeignKey(DeliveryDetail, on_delete=models.CASCADE, related_name="order")
    goods = models.ManyToManyField(Goods, related_name="order", blank=True)
    user_id = models.CharField()
    data_created = models.DateTimeField(auto_created=True, blank=True, null=True)

    @property
    def get_total_price(self):
        transaction = self.payment.filter(transaction_status="success").first()
        if transaction:
            return self.payment.filter(transaction_status="success").first().amount
        return None

    @property
    def get_currency(self):
        transaction = self.payment.filter(transaction_status="success").first()
        if transaction:
            return self.payment.filter(transaction_status="success").first().currency
        return None

payment/models.py
from django.db import models

from logistic.models import DeliveryDetail
from orders.models import Order


class Payments(models.Model):
    class TransactionStatus:
        success = "success"
        pending = "pending"
        failed = "failed"

    TRANSACTION_STATUS = (
        (TransactionStatus.success, "Success"),
        (TransactionStatus.pending, "Pending"),
        (TransactionStatus.failed, "Failed"),
    )

    amount = models.DecimalField(max_digits=10, decimal_places=2)
    currency = models.CharField()
    delivery_ditail = models.ForeignKey(DeliveryDetail, on_delete=models.CASCADE, related_name="payment")
    data_created = models.DateTimeField(auto_created=True)
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name="payment")
    transaction_status = models.CharField(choices=TRANSACTION_STATUS, default=TransactionStatus.pending)

    def __str__(self):
        return str(self.amount) + " " + self.currency

support/models.py
from django.db import models


class SupportRequest(models.Model):
    name = models.CharField(blank=True, null=True)
    email = models.EmailField(blank=False)
    topic = models.CharField(blank=False)
    payload = models.TextField(blank=True, null=True)
    date_created = models.DateField(auto_now_add=True, blank=True, null=True)
    response = models.TextField(blank=True, null=True)
    response_send = models.BooleanField(default=False)

    def __str__(self):
        return self.email

products/forms.py
from django import forms
from django.forms.models import inlineformset_factory
from .models import Product, ProductImages, ProductAttribute, Discount


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'brand', 'description', 'catalog_item', 'price', 'inventory']


ProductImagesFormset = inlineformset_factory(
    Product,
    ProductImages,
    fields=('image', 'main', 'color', 'price'),
    extra=20,
    can_delete=True
)


ProductAttributeFormset = inlineformset_factory(
    Product,
    ProductAttribute,
    fields=('name', 'value', 'title'),
    extra=150,
    can_delete=True
)

DiscountFormset = inlineformset_factory(
    Product,
    Discount,
    fields=('percentage', 'start_date', 'end_date',),
    extra=1,
    can_delete=False
)

basket/views.py
from django.db import transaction
from django.http import JsonResponse, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views import generic
from django.views.decorators.http import require_POST

from basket.models import Basket, Goods
from products.models import Product


class BasketView(generic.TemplateView):
    template_name = "shop/basket.html"

    def get_context_data(self, **kwargs):
        context = super(BasketView, self).get_context_data(**kwargs)
        user_id = self.request.COOKIES.get("user_id")

        basket, created = Basket.objects.get_or_create(user_id=user_id)
        for prev_goods in basket.goods.all():
            prev_goods.delete()
        for key, value in self.request.COOKIES.items():
            if key.startswith("basket"):
                product_id = key.split("_")[1]
                goods = Goods.objects.create(
                    product_id=product_id,
                    amount=value
                )
                basket.goods.add(goods)

        context["basket"] = basket
        return context


class PlusItemFromBasketView(generic.View):

    def update_cookie(self, response, product_id):
        for key, value in self.request.COOKIES.items():
            try:
                if key.startswith(f'basket_{product_id}'):
                    response.set_cookie(key, str(int(value) + 1))
            except ValueError as e:
                print(e)

    def get(self, request, product_id):
        user = self.request.COOKIES.get("user_id")
        basket = Basket.objects.get(user_id=user)
        response = redirect(request.META.get('HTTP_REFERER', '/'))
        with transaction.atomic():
            good = Goods.objects.get(basket=basket, product_id=product_id)
            if good.product.inventory < good.amount:
                good.amount += 1
                good.save()
                self.update_cookie(response, product_id)

        return response


class MinusItemFromBasketView(generic.View):

    def update_cookie(self, response, product_id):
        for key, value in self.request.COOKIES.items():
            try:
                if key.startswith(f'basket_{product_id}'):
                    response.set_cookie(key, str(int(value) - 1))
            except ValueError as e:
                print(e)

    def get(self, request, product_id):
        user = self.request.COOKIES.get("user_id")
        basket = Basket.objects.get(user_id=user)

        with transaction.atomic():
            good = Goods.objects.get(basket=basket, product_id=product_id)
            response = redirect(request.META.get('HTTP_REFERER', '/'))
            if good.amount > 1:
                good.amount -= 1
                good.save()
                self.update_cookie(response, product_id)
        return response


class DeleteItemFromBasketView(generic.View):

    def update_cookie(self, response, product_id):
        for key, value in self.request.COOKIES.items():
            try:
                if key.startswith(f'basket_{product_id}'):
                    response.delete_cookie(key)
            except ValueError as e:
                print(e)

    def post(self, request, product_id):
        user = self.request.COOKIES.get("user_id")
        basket = Basket.objects.get(user_id=user)

        with transaction.atomic():
            good = Goods.objects.filter(basket=basket, product_id=product_id).delete()
            response = redirect(request.META.get('HTTP_REFERER', '/'))
            self.update_cookie(response, product_id)
        return response

payment/views.py
import json

import stripe
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.utils import timezone
from django.views import generic

from basket.models import Basket
from django_shop import settings
from django_shop.settings import STRIPE_PUBLIC_KEY
from logistic.models import DeliveryDetail
from orders.models import Order
from payment.models import Payments
from products.models import Product
from site_detail.models import SiteDetail

site_details, created = SiteDetail.objects.get_or_create(id=1)
if site_details.stripe_private_key != "None":
    stripe.api_key = site_details.stripe_private_key
else:
    stripe.api_key = settings.STRIPE_SECRET_KEY


class CreatePaymentAPIView(generic.View):
    template_name = "shop/payment.html"

    def get(self, request, *args, **kwargs):
        site_details, created = SiteDetail.objects.get_or_create(id=1)
        if site_details.stripe_public_key != "None":
            context = {"stripe_public_key": site_details.stripe_public_key}
        else:
            context = {"stripe_public_key": STRIPE_PUBLIC_KEY}
        try:
            basket = Basket.objects.get(user_id=self.request.COOKIES.get("user_id"))
        except Basket.DoesNotExist:
            return reverse_lazy("basket:list")
        context["basket"] = basket
        return render(request, self.template_name, context=context)

    def post(self, request, *args, **kwargs):
        user_id = self.request.COOKIES.get("user_id")
        data = json.loads(request.body.decode('utf-8'))
        payment_method_id = data.get('payment_method_id')
        try:
            site_detail = SiteDetail.objects.get(id=1)
            site_currency = site_detail.currency.lower()
            if site_currency == "uan":
                site_currency = "uah"
            if site_currency == "euro":
                site_currency = "eur"
        except SiteDetail.DoesNotExist:
            site_currency = 'usd'
        try:
            basket = Basket.objects.get(user_id=user_id)
        except Basket.DoesNotExist:
            return redirect("basket:list")
        try:
            delivery_info = DeliveryDetail.objects.get(user_id=user_id)
        except DeliveryDetail.DoesNotExist:
            return JsonResponse(
                {
                    'message': 'Payment not confirmed',
                    'redirect_url': reverse('logistic:create-update-delivery-ditail')
                }
            )
        except DeliveryDetail.MultipleObjectsReturned:
            delivery_info = DeliveryDetail.objects.filter(user_id=user_id).last()

        payment_amount = int(basket.get_basket_total_price * 100)

        try:
            payment_intent = stripe.PaymentIntent.create(
                amount=payment_amount,
                currency=site_currency,
                confirm=True,
                payment_method=payment_method_id,
                return_url=request.build_absolute_uri(reverse('home')),
            )

        except stripe.error.CardError as e:
            return JsonResponse({'message': str(e)})

        if payment_intent.status == 'succeeded':
            order = Order.objects.create(
                delivery_status="created",
                delivery_info=delivery_info,
                user_id=user_id,
                data_created=timezone.now()
            )
            Payments.objects.create(
                amount=payment_amount // 100,
                currency=site_currency,
                delivery_ditail=delivery_info,
                order=order,
                transaction_status="success",
                data_created=timezone.now()
            )

            for goods in basket.goods.all():
                order.goods.add(goods)
                product = Product.objects.get(goods=goods)
                product.inventory -= goods.amount
                product.save()

            order.save()
            basket.goods.clear()
            basket.save()

            response_data = {'message': 'Payment successful', 'redirect_url': reverse('orders:user-order-list')}
            response = JsonResponse(response_data)

            for cookie_name in list(request.COOKIES.keys()):
                if cookie_name.startswith('basket'):
                    response.delete_cookie(cookie_name)

            return response
        else:
            return JsonResponse({'message': 'Payment not confirmed'})


class PaymentHistoryView(generic.ListView):
    model = Payments
    queryset = Payments.objects.all().order_by("-data_created")
    template_name = 'adminPanel/payments-history.html'
    paginate_by = 20

support/views.py
from django.db import transaction
from django.shortcuts import render, redirect
from django.views import generic

from django_shop import settings
from notifications.tasks import send_email_task
from support.models import SupportRequest


class ContactUsView(generic.View):
    def get(self, request, *args, **kwargs):
        return render(request=request, template_name="shop/support.html")

    def post(self, request, *args, **kwargs):

        if SupportRequest.objects.filter(
                email=self.request.POST.get("email"),
                topic=self.request.POST.get("topic"),
                name=self.request.POST.get("name"),
                payload=self.request.POST.get("payload"),
        ).exists():
            context = {"status": "Failed"}
        else:
            SupportRequest.objects.create(
                name=self.request.POST.get("name"),
                email=self.request.POST.get("email"),
                topic=self.request.POST.get("topic"),
                payload=self.request.POST.get("payload"),
            )
            context = {"status": "Success"}
        return render(request=request, template_name="shop/support.html", context=context)


class AdminSupportListView(generic.ListView):
    model = SupportRequest
    queryset = SupportRequest.objects.all().order_by("response_send")
    paginate_by = 10
    template_name = "adminPanel/supportPage.html"


class SendSupportResponseView(generic.View):

    def post(self, request, *args, **kwargs):
        with transaction.atomic():
            support_id = self.kwargs.get("id")
            support = SupportRequest.objects.get(id=support_id)
            support.response_send = True
            support.response = self.request.POST.get("response")
            support.save()
            send_email_task.delay(settings.SUPPORT_RESPONSE, {"data": support.response}, support.email)

        return redirect('support:admin-support')

templates/shop/basket.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<div id="basketDetail" >
<div>
{% for prodact in basket.goods.all %}
  <div class="basketDitailContainer">
  {% for image in prodact.product.images.all %}

    {% if image.main %}
      <img class="basketProductImage" src="{{ image.image.url }}" alt="{{ prodact.product.name }}">
    {% endif %}
  {% empty %}
    <img class="basketProductImage" src="{% static 'images/default-product-item.png' %}" alt="{{ prodact.product.name }}">
  {% endfor %}
  <div class="basketProductName">
    {{ prodact.product.name }}
    <div class="basketProductDescription">{{ prodact.product.description }}</div>
  </div>
  <div style="display: flex; flex-flow: column">
    {% if prodact.product.inventory >= prodact.amount %}
      <div class="available" style="color: #4CAF50">Available</div>
    {% else %}
      <div class="available" style="color: red">Not enough stock available</div>
    {% endif %}
    {% if  prodact.product.get_discount_price %}
      <div class="basketProductPrice">Discount price: {{ prodact.product.get_discount_price }} {{ site.get_currency_display }}</div>
    {% else %}
    <div class="basketProductPrice">Price: {{ prodact.product.price }} {{ site.get_currency_display }}</div>
    {% endif %}
    <div class="basketProductPrice">Brand: {{ prodact.product.brand }}</div>
  </div>
<div class="basketIconIn" style="display: flex">
  <span class="operator plusBasketItem"
      data-product-id="{{ product.product.id }}"
      data-update-url="{% url 'basket:plus_basket' prodact.product.id %}"
      onclick="window.location.href = this.getAttribute('data-update-url');">+</span>
  <div><i class="fas fa-shopping-basket fa-2x">{{ prodact.amount }}</i></div>
  <span class="operator minusBasketItem" data-product-id="{{ product.product.id }}"
      data-update-url="{% url 'basket:minus_basket' prodact.product.id %}"
      onclick="window.location.href = this.getAttribute('data-update-url');">-</span>
</div>
  <div class="itemSum">Total:  {{ prodact.get_total|floatformat:"2" }} {{ site.get_currency_display }}</div>
 <form action="{% url 'basket:delete-item' prodact.product.id %}" method="post" style="display: inline;">
    {% csrf_token %}
    <button type="submit" class="delete-button" title="delete"></button>
  </form>

  </div>

{% empty %}
  {% include 'includes/basketEmptyPage.html' %}
{% endfor %}
</div>

  {% if basket.goods.all %}
    <div id="buyButtonContainer">
    <button id="buyButton" onclick="redirectToDeliveryDetail('{% url 'logistic:create-update-delivery-ditail' %}')">Buy</button>
    </div>
    <script>
    function redirectToDeliveryDetail(url) {
        window.location.href = url;
    }
</script>
    <div>
    <div class="totalPrice">Total: {{ basket.get_basket_total_price|floatformat:"2" }} {{ site.get_currency_display }}</div>
    </div>
  {% endif %}

</div>

{% endblock %}

templates/shop/homepage.html
{% extends 'base.html' %}

{% block content %}
<div id="homeContainer">
{% for item in catalog_items %}
  <div class="catalogHomeItem" onclick="redirectToProductList({{ item.id }})"
       {% if item.image %}
       style="background-image: url({{ item.image.url }});"
       {% else %}
        style="background-image: url('/static/images/defoult-catalog-item.png');"
       {% endif %}
  >
  <script>
  function redirectToProductList(catalogItemId) {
    window.location.href = `{% url 'products:product-list' %}?catalog_item_id=${catalogItemId}`;
  }
</script>
  <div class="coverImage">
    <span class="catalogText">{{ item.name }}</span>
  </div>
  </div>

{% endfor %}

</div>
{% endblock %}

templates/shop/payment.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div id="loading-overlay">
    <div id="spinner"></div>
  </div>
   <div id="notification" class="notification"></div>
  <div class="formTitles" style="display: flex; justify-content: center; align-items: center;">
  <div id="deliveryTitle" class="tableTitle">Delivery Information</div>
  <div id="paymentTitle" class="tableTitle" style="background: greenyellow">Payment</div>
  </div>
 <div id="formContainer">
  <div>
    <img class="logisticPicture" src="{% static 'images/paymentPage.png' %}" alt="logistic picture">
  </div>
  <div id="divCard">
    <span id="paymentForm">Payment form</span>
  <form action="{% url 'payment:create-payment' %}" method="post" id="payment-form">
  {% csrf_token %}
  <div id="card-element">

  </div>


  <div id="card-errors" role="alert"></div>
    {% for goods in basket.goods.all %}
      <div id="productHolderPayment">
      <div class="goodsPicturePayment">
         {% for image in goods.product.images.all %}
          {% if image.main %}
            <img class="goodImagePayment" src="{{ image.image.url }}" alt="{{ prodact.product.name }}">
          {% endif %}
          {% empty %}
            <img class="goodImagePayment" src="{% static 'images/default-product-item.png' %}" alt="{{ prodact.product.name }}">
          {% endfor %}
      </div>
      <div class="goodsInfoPayment">
        <div>Name: {{ goods.product.name }}</div>
        <div>Amount: {{ goods.amount }}</div>
        <div>Total: <span style="color: #4CAF50">{{ goods.get_total }} {{ site.get_currency_display }}</span></div>
      </div>
      </div>
    {% endfor %}

  <div id="totalPricePayment">Total: <span style="color: green"> {{ basket.get_basket_total_price }} {{ site.get_currency_display }}</span></div>

  <button id="buyBasket">Submit Payment</button>
  </form>

  <script src="https://js.stripe.com/v3/"></script>

    <script>
      var form = document.getElementById('payment-form');
      var loadingOverlay = document.getElementById('loading-overlay');

      var stripe = Stripe('{{ stripe_public_key }}');
      var elements = stripe.elements();

      var card = elements.create('card');
      card.mount('#card-element');

      var form = document.getElementById('payment-form');
      form.addEventListener('submit', function(event) {
          event.preventDefault();
          loadingOverlay.style.display = 'flex';
          stripe.createPaymentMethod({
              type: 'card',
              card: card,
          }).then(function(result) {
              if (result.error) {
                  console.log('Error:', result.error);
              } else {
                  fetch('{% url 'payment:create-payment' %}', {
                      method: 'POST',
                      headers: {
                          'Content-Type': 'application/json',
                          'X-CSRFToken': getCookie('csrftoken'),
                      },
                      body: JSON.stringify({ payment_method_id: result.paymentMethod.id })
                  })
                  .then(function(response) {
                      return response.json();
                  })
                  .then(function(responseJson) {
                      console.log('Server response:', responseJson);

                      if (responseJson.message === 'Payment successful') {
                          if (responseJson.redirect_url) {
                              window.location.href = responseJson.redirect_url;
                          } else {
                              window.location.reload();
                          }
                      } else {
                          console.log('Payment failed!');
                          showNotification('Payment failed!', false);
                      }
                  })
                  .catch(function(error) {
                      console.error('Error during fetch:', error);
                  })
                  .finally(function() {
                  loadingOverlay.style.display = 'none';
              });

              }
          }).catch(function(error) {
              console.error('Error creating payment method:', error);
          });
      });

       function getCookie(name) {
          var value = "; " + document.cookie;
          var parts = value.split("; " + name + "=");
          if (parts.length == 2) return parts.pop().split(";").shift();
        }
          </script>

  </div>
</div>

{% endblock %}

templates/shop/products-item.html
{% load static %}
{% load custom_filters %}

<div class="productCustomerContainer">
<script>
    document.querySelectorAll('.imageContainerList').forEach(item => {
        item.addEventListener('click', function() {
            window.location.href = this.getAttribute('data-url');
        });
    });
</script>
    <div id="notification" class="notification"></div>
{% if product.inventory <= 0 %}
  <div class="overlay">
  <div class="notAvailableNow">Not available now</div>
  </div>
{% endif %}
<div class="imageContainerList" data-url="{% url 'products:product_detail' product.id %}">
    {% if product.get_discount %}
      <div class="discountProcentList"> - {{ product.get_discount }} % </div>
    {% endif %}
   {% for image in product.images.all %}
    {% if image.main %}
      <img class="productImageList" src="{{ image.image.url }}" alt="{{ product.name }}">
    {% endif %}
  {% empty %}
    <img class="productImageList" src="{% static 'images/default-product-item.png' %}" alt="{{ product.name }}">
  {% endfor %}
  </div>
    <div class="flexBoxProduct">
      <div class="productNameList">Name: {{ product.name }}</div>
      <div style="display: flex; align-self: flex-start; margin-left: 15px">
         <div class="starRatingList"  data-product-id="{{ product.id }}">
            <span class="starList star1List" data-value="1">☆</span>
            <span class="starList star2List" data-value="2">☆</span>
            <span class="starList star3List" data-value="3">☆</span>
            <span class="starList star4List" data-value="4">☆</span>
            <span class="starList star5List" data-value="5">☆</span>
        </div>
        <div>
           <i class="fas fa-comment commentIcon" data-product-id="{{ product.id }}"></i>
        </div>
      </div>
      <div class="priceProductList">
        <span style="{% if product.get_discount_price %}text-decoration: line-through; color: red;{% endif %}">
        Price: {{ product.price }} {{ site.get_currency_display }}
        </span>
      </div>

      {% if product.get_discount_price %}
        <div class="discountList">
          <span style="color: darkgreen"> Discount price: {{ product.get_discount_price }} {{ site.get_currency_display }}</span>
        </div>
      {% endif %}

      <div class="productBasket">
        <span class="plusBasket basketSymbol" data-product-id="{{ product.id }}" onclick="addToBasket(this, {{ product.inventory }})">+</span>
        <i id="basket-{{ product.id }}" class="fas fa-shopping-basket"></i>
        <span class="minusBasket basketSymbol" data-product-id="{{ product.id }}" onclick="removeFromBasket(this)">-</span>
      </div>
    </div>
</div>

<script>
  function addToBasket(element, productInventory) {
      let productId = element.getAttribute('data-product-id');
      let basket = document.getElementById(`basket-${productId}`);
      let count = getBasketCount(productId);
      if (count < productInventory) {
          count++;
          basket.innerText = count;
          setBasketCount(productId, count);
          let mainBasket = document.getElementById("mainBasketIcon")
          mainBasket.innerText++
      } else {
          showNotification("Insufficient stock!", false);
      }
  }

  function removeFromBasket(element) {
    let productId = element.getAttribute('data-product-id');
    let basket = document.getElementById(`basket-${productId}`);
    let count = getBasketCount(productId);
    if (count > 0) {
      count--;
      basket.innerText = count;
      setBasketCount(productId, count);
      let mainBasket = document.getElementById("mainBasketIcon")
      mainBasket.innerText--
    }
  }

  function setBasketCount(productId, count) {
    if (count === 0) {
      document.cookie = `basket_${productId}=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/`;
    } else {
      document.cookie = `basket_${productId}=${count}; expires=Fri, 31 Dec 9999 23:59:59 GMT; path=/`;
    }
  }

  function getBasketCount(productId) {
    let name = `basket_${productId}=`;
    let decodedCookie = decodeURIComponent(document.cookie);
    let cookieArray = decodedCookie.split(';');
    for (let i = 0; i < cookieArray.length; i++) {
      let cookie = cookieArray[i].trim();
      if (cookie.indexOf(name) === 0) {
        return parseInt(cookie.substring(name.length)) || 0;
      }
    }
    return 0;
  }

  window.onload = function() {
    let productIds = Array.from(document.querySelectorAll('.plusBasket, .minusBasket')).map(element => element.getAttribute('data-product-id'));
    productIds.forEach(productId => {
      let basket = document.getElementById(`basket-${productId}`);
      let count = getBasketCount(productId);
      basket.innerText = count;
    });
  };
</script>

templates/shop/support.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  {% if status %}
    <script>
      document.addEventListener('DOMContentLoaded', function() {
          var notification = document.getElementById('notificationSupport');
          if (notification) {
              notification.style.display = 'block';
              setTimeout(function() {
                  notification.style.display = 'none';
              }, 3000);
          }
        });
      </script>
    <div id="notificationSupport" {% if status == "Failed" %} style="background-color: red" {% endif %}>
        {{ status }}
    </div>
  {% endif %}

  <div class="aboutUsContentContainer">
  <div class="supportBlock">
    <img class="supportImage" src="{% static 'images/support.png' %}" alt="Support">

    <div class="form-container supportForm">
      <form method="post" action="{% url "support:contact-us" %}">
        {% csrf_token %}
        <h2 class="titleAboutUs">Support</h2>
              <div class="supportDiv" style="display: flex">
        <div style="text-align: left; margin-right: 0">Name:</div>
        <input class="supportInput" name="name">
      </div>
      <div class="supportDiv" style="display: flex">
        <div style="text-align: left; margin-right: 0;">Email:</div>
        <input class="supportInput" name="email" required="True">
      </div>
      <div class="supportDiv" style="display: flex">
        <div style="text-align: left; margin-right: 0">Topic:</div>
        <input class="supportInput" name="topic" required="True">
      </div>
      <div class="supportDiv" style="display: flex">
        <div style="text-align: left; margin-right: 0">Payload:</div>
        <textarea class="supportInput" name="payload"></textarea>
      </div>
        <div class="button-container">
      <button class="supportButton formButton" type="submit">Send</button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}